name: Deploy App

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Authorizing Github action
      with:
        token: "${{ secrets.GH_PAGES }}"
      uses: oleksiyrudenko/gha-git-credentials@v1
#     - name: Use Node.js
#       uses: actions/setup-node@v1
#       with:
#         node-version: '14.x'
#     - run: git config --global user.email "you@example.com"
#     - run: git config --global user.name "Your Name"
#     - run: npm install
#     - run: npm run deploy
